=== MarvinEsteban/WebFiralia/XML/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Fet per: Joan Marc -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="lastname" type="xs:string"/>
                            <xs:element name="age" type="xs:integer"/>
                            <xs:element name="profile_image" type="xs:string"/>
                            <xs:element name="register_date" type="xs:date"/>
                            <xs:element name="about" type="xs:string"/>
                        </xs:sequence>
                        <!-- AÃ±adimos el atributo "id" al elemento "user" -->
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MarvinEsteban/WebFiralia/XML/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Fet per: Joan Marc-->

<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="users.xsd">
    <user>
        <name></name>
        <lastname></lastname>
        <age></age>
        <profile_image></profile_image>
        <register_date></register_date>
        <about></about>
    </user>
</users>
